# Generated by Django 3.1.7 on 2021-05-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(default='0', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mob_number', models.IntegerField(max_length=10)),
                ('book_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
