# Generated by Django 3.1.7 on 2021-05-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='name',
            new_name='person_name',
        ),
    ]
