# Generated by Django 3.1.7 on 2021-05-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbs', '0003_auto_20210507_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='table_id',
        ),
        migrations.AddField(
            model_name='table',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
