# Generated by Django 3.1.7 on 2021-05-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbs', '0005_auto_20210507_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='mob_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='person_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
