# Generated by Django 3.1.7 on 2021-05-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbs', '0009_table_remain_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='remain_tables',
            field=models.CharField(default=12, max_length=2),
        ),
    ]
