# Generated by Django 3.1.7 on 2021-05-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbs', '0010_auto_20210511_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='remain_tables',
            field=models.IntegerField(default=12, max_length=2),
        ),
    ]
